config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'
  get 'doses/new' => 'dose#new'

  get 'doses/create' => 'dose#create'

  get 'doses/destroy' => 'dose#destroy'

  get 'cocktails/index' => 'cocktails#index'

  get 'cocktails/show' => 'cocktails#show'

  get 'cocktails/new' => 'cocktails#new'

  get 'cocktails/create' => 'cocktails#create'

  get 'cocktails/destroy' => 'cocktails#destroy'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :dose
  validates :name, presence: :true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :coktails
  belongs_to :ingredients
  validates :description, presence: :true
  validates_uniqueness_of :Ingredient_id, scope: [:cocktail_id]

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :dose

  validates :name, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show, :destroy ]
  def index
    @coktail = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Coktail.destroy(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

private

def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController


  def new
    @dose = Dose.new
  end

  def create
  end

    def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end

 private

  def dose_params
    params.require(:dose).permit(:amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/index.html.erb
<h1>Cocktails#index</h1>
<p>Find me in app/views/cocktails/index.html.erb</p>

<h1>Cocktails</h1>

<% @cocktails.each do |c| %>
  <h2>
    <%= link_to c.name, cocktail_path(c) %>
  </h2>
<% end %>

<%= link_to "Add a cocktail", cocktails_new_path, class: "btn btn-primary" %>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>

app/views/cocktails/show.html.erb
<h1>Cocktails#show</h1>
<p>Find me in app/views/cocktails/show.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktailLast</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>